module.exports = {
  apps: [
    {
      name: 'learnmind-backend',
      script: 'dist/main.js',
      cwd: '/home/sw1/pryectofinalverano/backend',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: '/home/sw1/pryectofinalverano/logs/backend-error.log',
      out_file: '/home/sw1/pryectofinalverano/logs/backend-out.log',
      log_file: '/home/sw1/pryectofinalverano/logs/backend-combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'learnmind-frontend',
      script: 'npx',
      args: ['serve', 'dist', '-s', '-p', '5173'],
      cwd: '/home/sw1/pryectofinalverano/frontend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      error_file: '/home/sw1/pryectofinalverano/logs/frontend-error.log',
      out_file: '/home/sw1/pryectofinalverano/logs/frontend-out.log',
      log_file: '/home/sw1/pryectofinalverano/logs/frontend-combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'learnmind-ocr',
      script: '/home/sw1/pryectofinalverano/backend/venv_ocr/bin/python3',
      args: '/home/sw1/pryectofinalverano/backend/scripts/paddle_ocr_service.py',
      cwd: '/home/sw1/pryectofinalverano/backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: {
        PYTHONUNBUFFERED: '1',
      },
      error_file: '/home/sw1/pryectofinalverano/logs/ocr-error.log',
      out_file: '/home/sw1/pryectofinalverano/logs/ocr-out.log',
      log_file: '/home/sw1/pryectofinalverano/logs/ocr-combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
