module.exports = {
  apps: [
    {
      name: 'learnmind-backend',
      script: 'dist/main.js',
      cwd: '/opt/learnmind-ai/backend',
      instances: 2,
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: '/opt/learnmind-ai/logs/backend-error.log',
      out_file: '/opt/learnmind-ai/logs/backend-out.log',
      log_file: '/opt/learnmind-ai/logs/backend-combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'learnmind-frontend',
      script: 'serve',
      cwd: '/opt/learnmind-ai/frontend',
      env: {
        PM2_SERVE_PATH: 'dist',
        PM2_SERVE_PORT: 5173,
        PM2_SERVE_SPA: 'true',
        PM2_SERVE_HOMEPAGE: '/index.html',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      error_file: '/opt/learnmind-ai/logs/frontend-error.log',
      out_file: '/opt/learnmind-ai/logs/frontend-out.log',
      log_file: '/opt/learnmind-ai/logs/frontend-combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'learnmind-ocr',
      script: '/opt/learnmind-ai/backend/venv_ocr/bin/python3',
      args: '/opt/learnmind-ai/backend/scripts/paddle_ocr_service.py',
      cwd: '/opt/learnmind-ai/backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env: {
        PYTHONUNBUFFERED: '1',
      },
      error_file: '/opt/learnmind-ai/logs/ocr-error.log',
      out_file: '/opt/learnmind-ai/logs/ocr-out.log',
      log_file: '/opt/learnmind-ai/logs/ocr-combined.log',
      time: true,
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
